/*
 * File: app/view/CreatePOIWindow.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('POIManager.view.CreatePOIWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.createpoiwindow',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.FieldContainer',
        'Ext.form.field.Display',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill'
    ],

    height: 250,
    width: 400,
    resizable: false,
    layout: 'fit',
    title: 'Create POI',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    defaults: {
                        hideLabel: true
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            itemId: 'txtName',
                            width: 250,
                            fieldLabel: 'Label',
                            name: 'Name',
                            allowBlank: false,
                            allowOnlyWhitespace: false,
                            emptyText: 'Enter a POI Name',
                            maxLength: 100
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'txtAddress',
                            fieldLabel: 'Label',
                            name: 'Address',
                            emptyText: 'Enter an Address (optional)'
                        },
                        {
                            xtype: 'fieldcontainer',
                            defaults: {
                                hideLabel: true
                            },
                            fieldLabel: 'Label',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'displayfield',
                                    flex: 0.5,
                                    itemId: 'lblLat',
                                    fieldLabel: 'Label',
                                    name: 'Lat'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 0.5,
                                    itemId: 'lblLOn',
                                    fieldLabel: 'Label',
                                    name: 'Lon'
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    defaultButtonUI: 'default',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnCancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnCreate',
                            text: 'Create'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});