/*
 * File: app/view/POIList.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('POIManager.view.POIList', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.poilist',

    requires: [
        'Ext.grid.column.Column',
        'Ext.grid.View'
    ],

    width: 200,
    store: 'POI',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Name',
                    text: 'POI Database',
                    flex: 1
                }
            ]
        });

        me.callParent(arguments);
    }

});