/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true,
    paths: {
        Ext: 'http://static.pinpointers.com/Lib/Sencha/ExtJS/4.2.1/src'
    }
});


Ext.application({

    requires: [
        'Ext.Loader',
        'Ext.layout.container.Border'
    ],
    models: [
        'POI'
    ],
    stores: [
        'POI'
    ],
    views: [
        'MyViewport',
        'MapPanel',
        'POIList',
        'CreatePOIWindow'
    ],
    controllers: [
        'MapController'
    ],
    name: 'POIManager',

    launch: function() {
        Ext.create('POIManager.view.MyViewport');
    }

});
